import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import Header from "../components/Header"
// import Footer from "../components/Footer"
 


// Local font configurations
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Page metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/favicon.png", // Ensure the favicon is in the public folder under /assets/img/
  },
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
  <meta charSet="utf-8" />
  <meta httpEquiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  
  {/* Site Title */}
  <title>Runok - Web Agency HTML5 Template</title>
  {/* Place favicon.ico in the root directory */}
  <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png" />
  {/* CSS here */}
  <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
  <link rel="stylesheet" href="assets/css/fontawesome.min.css" />
  <link rel="stylesheet" href="assets/css/venobox.min.css" />
  <link rel="stylesheet" href="assets/css/animate.min.css" />
  <link rel="stylesheet" href="assets/css/keyframe-animation.css" />
  <link rel="stylesheet" href="assets/css/odometer.min.css" />
  <link rel="stylesheet" href="assets/css/nice-select.css" />
  <link rel="stylesheet" href="assets/css/swiper.min.css" />
  <link rel="stylesheet" href="assets/css/main.css" />
 

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
        <Header/>

        
        {/* <Footer/> */}

        {/* Adding scripts using next/script */}
        <Script src="assets/js/vendor/jquary-3.6.0.min.js"></Script>
        <Script src="assets/js/vendor/bootstrap-bundle.js"></Script>
        <Script src="assets/js/vendor/imagesloaded-pkgd.js"></Script>
        <Script src="assets/js/vendor/waypoints.min.js"></Script>
        <Script src="assets/js/vendor/venobox.min.js"></Script>
        <Script src="assets/js/vendor/odometer.min.js"></Script>
        <Script src="assets/js/vendor/meanmenu.js"></Script>
        <Script src="assets/js/vendor/jquery.isotope.js"></Script>
        <Script src="assets/js/vendor/wow.min.js"></Script>
        <Script src="assets/js/vendor/swiper.min.js"></Script>
        <Script src="assets/js/vendor/split-type.min.js"></Script>
        <Script src="assets/js/vendor/gsap.min.js"></Script>
        <Script src="assets/js/vendor/scroll-trigger.min.js"></Script>
        <Script src="assets/js/vendor/scroll-smoother.js"></Script>
        <Script src="assets/js/vendor/jquery.carouselTicker.js"></Script>
        <Script src="assets/js/vendor/nice-select.js"></Script>
        <Script src="assets/js/ajax-form.js"></Script>
        <Script src="assets/js/contact.js"></Script>
        <Script src="assets/js/main.js"></Script>
     

      </body>
    </html>
  );
}
